{
 "title": "Wireguard",
 "description": "Wireguard Dashboard",
 "time": { "from": "now-80m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interface",
    "label": "接口",
    "query": "label_values(wireguard_device_info, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "接口信息",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "wireguard_device_info{device=~\"$interface\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Peer 信息",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "wireguard_latest_handshake_seconds{interface=~\"$interface\"} * 1000 * on (public_key) group_left(name) wireguard_peer_info"
    }
   ]
  },
  {
   "title": "Last Handshake",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - wireguard_peer_last_handshake_seconds{device=~\"$interface\"} * on (public_key, device) group_left(name) wireguard_peer_info{name!=\"\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "time() - label_replace(wireguard_latest_handshake_seconds{interface!=\"wg0\", interface=~\"$interface\", remote_ip!=\"\"}, \"public_key\", \"$1\", \"\", \"\")",
     "legendFormat": "{{remote_ip}}"
    }
   ]
  },
  {
   "title": "与 Peer 的最新握手时间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - wireguard_peer_last_handshake_seconds{device=~\"$interface\"} * on (public_key, device) group_left(name) wireguard_peer_info{name!=\"\"} < 180",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "time() - label_replace(wireguard_latest_handshake_seconds{interface!=\"wg0\", interface=~\"$interface\", remote_ip!=\"\"}, \"public_key\", \"$1\", \"\", \"\") < 180",
     "legendFormat": "{{remote_ip}}"
    }
   ]
  },
  {
   "title": "网卡上行流量(1m)",
   "type": "graph",
   "description": "1分钟内平均每秒发送给 peer 的流量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(wireguard_peer_transmit_bytes_total{device=~\"$interface\"}[1m])  * on (public_key, device) group_left(name) wireguard_peer_info{name!=\"\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(irate(wireguard_sent_bytes_total{interface!=\"wg0\", interface=~\"$interface\"}[1m])) by (interface)",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "网卡下行流量(1m)",
   "type": "graph",
   "description": "1分钟内平均每秒接收的 peer 流量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(wireguard_peer_receive_bytes_total{device=~\"$interface\"}[1m])  * on (public_key, device) group_left(name) wireguard_peer_info{name!=\"\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(irate(wireguard_received_bytes_total{interface!=\"wg0\", interface=~\"$interface\"}[1m])) by (interface)",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "wg0 网卡上行流量(1m)",
   "type": "graph",
   "description": "1分钟内平均每秒发送给 peer 的流量",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(wireguard_peer_transmit_bytes_total{device=\"wg0\"}[1m])  * on (public_key, device) group_left(name) wireguard_peer_info{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "wg0 网卡下行流量(1m)",
   "type": "graph",
   "description": "1分钟内平均每秒接收的 peer 流量",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(wireguard_peer_receive_bytes_total{device=\"wg0\"}[1m]) * on (public_key, device) group_left(name) wireguard_peer_info{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}