#!/bin/bash
set -eo pipefail

sed -i \
  -e "s/^eid.*/eid=$JD_SECKILL_EID/g" \
  -e "s/^fp.*/fp=$JD_SECKILL_FP/g" \
  -e "s/^sku_id.*/sku_id=$JD_SECKILL_SKU_ID/g" \
  -e "s/^buy_time.*/buy_time=$JD_SECKILL_BUY_TIME/g" \
  -e "s/^default_user_agent.*/default_user_agent=$JD_SECKILL_DEFAULT_USER_AGENT/g" \
  -e "s/^random_useragent.*/random_useragent=$JD_SECKILL_RANDOM_USERAGENT/g" \
  -e "s/^payment_pwd.*/payment_pwd=$JD_SECKILL_PAYMENT_PWD/g" \
  -e "s/^server_chan_enable.*/server_chan_enable=$JD_SECKILL_SERVER_CHAN_ENABLE/g" \
  -e "s/^server_chan_sckey.*/server_chan_sckey=$JD_SECKILL_SERVER_CHAN_SCKEY/g" \
  -e "s/^email_enable.*/email_enable=$JD_SECKILL_EMAIL_ENABLE/g" \
  -e "s/^email_host.*/email_host=$JD_SECKILL_EMAIL_HOST/g" \
  -e "s/^email_user.*/email_user=$JD_SECKILL_EMAIL_USER/g" \
  -e "s/^email_pwd.*/email_pwd=$JD_SECKILL_EMAIL_PWD/g" \
  -e '/#/d' \
  /app/config.ini;

if [ "${1:0:1}" = "-" ]; then
	set -- python "$@"
fi

if [ "$1" = "reserve" ]; then
	echo 1 | python main.py
fi

if [ "$1" = "seckill" ]; then
	echo 2 | python main.py
fi

exec "$@"
