name: Build and push palworld-server-tool Docker image

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build-docs-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker images to ghcr.io and Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: palworld-server-tool
          platforms: linux/amd64
          file: 'palworld-server-tool/Dockerfile'
          push: true
          tags: |
            yangchuansheng/palworld-server-tool:latest
            ghcr.io/yangchuansheng/palworld-server-tool:latest
