name: Build and push solana-rpc-proxy Docker image

on:
  workflow_dispatch:
  push:
      branches: [ master ]
      paths:
        - 'solana-rpc-proxy/**'
        - '.github/workflows/solana-rpc-proxy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker images to ghcr.io and DockerHub
        uses: docker/build-push-action@v5
        with:
          context: ./solana-rpc-proxy
          file: ./solana-rpc-proxy/Dockerfile
          push: true
          tags: |
            yangchuansheng/solana-rpc-proxy:latest
            ghcr.io/yangchuansheng/solana-rpc-proxy:latest